name: papercups_flutter
description: Native Flutter implementation of the papercups.io chat widget.
version: 3.1.1
homepage: https://github.com/aguilaair/papercups_flutter

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket: ^0.7.6
  http: ^1.2.2
  universal_io: ^2.0.4
  flutter_markdown: ^0.7.4+3
  timeago: ">=2.0.30 <4.0.0"
  intl: ^0.20.1
  file_picker: 8.1.4
  path_provider: ^2.0.1
  url_launcher: ^6.1.2
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.1
  build_runner: ">=1.12.2 <3.0.0"
  flutter_lints: ^5.0.0

flutter:
